# Default values for my-app chart
imageTag: latest  # Default tag, will be overridden by CI/CD

frontend:
  image:
    repository: muzaparoff/lab-eks-cluster-frontend
    # tag will be set by ArgoCD from versions.json
  replicas: 2

backend:
  image:
    repository: muzaparoff/lab-eks-cluster-backend
    # tag will be set by ArgoCD from versions.json
  replicas: 2

service:
  internalDomain: "app.internal.example.com"