apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: lab-app
  namespace: argocd
spec:
  description: Lab Application Project
  sourceRepos:
  - '*'
  destinations:
  - namespace: lab-app
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
