name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

env:
  AWS_REGION: us-east-1
  TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
      - uses: actions/checkout@v3

      - name: Load versions
        id: versions
        run: |
          VERSION_FILE="versions.json"
          if [[ -f "$VERSION_FILE" ]]; then
            echo "infra_version=$(jq -r .infra_version $VERSION_FILE)" >> $GITHUB_OUTPUT
            echo "app_version=$(jq -r .app_version $VERSION_FILE)" >> $GITHUB_OUTPUT
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Terraform Plan/Apply/Destroy
        run: |
          cd terraform
          if [[ "${{ github.event.inputs.action }}" == "destroy" ]]; then
            terraform destroy -auto-approve
          else
            terraform plan
            terraform apply -auto-approve
          fi

  deploy-application:
    needs: deploy-infrastructure
    if: ${{ github.event.inputs.action != 'destroy' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Load versions
        id: versions
        run: |
          VERSION_FILE="versions.json"
          if [[ -f "$VERSION_FILE" ]]; then
            echo "app_version=$(jq -r .app_version $VERSION_FILE)" >> $GITHUB_OUTPUT
          fi

      - name: Install ArgoCD CLI
        run: |
          curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          sudo install -m 555 argocd-linux-amd64 /usr/local/bin/argocd
          rm argocd-linux-amd64

      - name: Deploy with ArgoCD
        run: |
          aws eks update-kubeconfig --name lab-eks-cluster --region $AWS_REGION
          kubectl apply -f k8s/argocd-app.yaml
          
          # Wait for app sync
          kubectl wait --for=condition=ready -n argocd application/lab-app --timeout=300s
